// <auto-generated />
namespace ProjectArcive_DIU.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "202003291003200_userEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
